site_name: IKAL
site_description: Reference du langage IKAL
docs_dir: docs
site_dir: site
nav:
  - Accueil: index.md
  - Langage:
      - Syntaxe: syntaxe.md
      - Vocabulaire: mots.md
      - Migration POC: migration-poc.md
      - Paramètres artistiques: params.md
      - Notes techniques: langage.md
theme:
  name: mkdocs
strict: true
